name: Build Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install deps
      run: sudo apt-get update && sudo apt-get install pandoc

    - name: build site
      run: make clean && make

    - name: deploy back to gh
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -n "$GITHUB_HEAD_REF" ]; then git checkout "$GITHUB_HEAD_REF"; fi
        git config --local user.name "GitHub Actions"
        git config --local user.email "<>"
        git checkout gh-pages
        git pull --rebase origin master
        make clean && make
        git add -f docs/
        git commit -m 'GitHub Actions: build site' || echo 'nothing to commit'
        git push -f origin gh-pages || echo 'nothing to push'
